vires/vires/processes/retrieve_data.py

* Reduced amount of bands written to CSV as they were not used in any case
* Added conceptual very basic "dynamic" subset concept
* Removed building of difference when two collections are selected as we should discuss the best way to provide difference building in the user interface and on the server, it is not a good way how it was done until now

Adaptation of retrieve swarm data

---

eoxs_allauth/eoxs_allauth/decorators.py
eoxs_allauth/eoxs_allauth/views.py
vires/vires/mapserver/connectors/fm_connector.py
vires/vires/processes/base.py
vires/vires/processes/eval_model.py
vires/vires/processes/eval_model_diff.py
vires/vires/processes/get_indices.py
vires/vires/processes/retrieve_data.py
vires/vires/processes/retrieve_data_filtered.py
vires/vires/processes/retrieve_field_lines.py

Information about the accessed data, processed and user accessing these resources are logged to a dedicated access log.

Implementing server-side access logging.

---

eoxs_allauth/README.md
eoxs_allauth/eoxs_allauth/__init__.py
eoxs_allauth/eoxs_allauth/apps.py
eoxs_allauth/eoxs_allauth/decorators.py
eoxs_allauth/eoxs_allauth/forms.py
eoxs_allauth/eoxs_allauth/middleware.py
eoxs_allauth/eoxs_allauth/models.py
eoxs_allauth/eoxs_allauth/signals.py
eoxs_allauth/eoxs_allauth/url_tools.py
eoxs_allauth/eoxs_allauth/urls.py
eoxs_allauth/eoxs_allauth/views.py

Key features:
- full-fledged access logging + sign-up/authentication monitoring
- reworked URL configuration
- improved user-name extrapolation from the social account data
- general code review and code style improvements

eoxs_allauth review

---

vires/vires/cdf_util.py
vires/vires/processes/fetch_data.py
vires/vires/processes/retrieve_bubble_index.py
vires/vires/processes/util/__init__.py
vires/vires/processes/util/dataset.py
vires/vires/processes/util/filters.py
vires/vires/processes/util/filters_subsampling.py
vires/vires/processes/util/input_parsers.py
vires/vires/processes/util/interpolate.py
vires/vires/processes/util/model.py
vires/vires/processes/util/model_magmod.py
vires/vires/processes/util/model_qd_mlt.py
vires/vires/processes/util/png_output.py
vires/vires/processes/util/time_series.py
vires/vires/processes/util/time_series_aux.py
vires/vires/processes/util/time_series_product.py
vires/vires/tests/cdf_util.py
vires/vires/time_util.py
vires/vires/util.py

* New process to retrieve data from multiple types and merge them together for visualization
* New process to provide data of where IBI probability above 0.1

Merged product download

---

vires/vires/processes/fetch_data.py

* Getting better results when doing localized selection

Slightly modified the subsampling algorithm

---

vires/vires/processes/util/filters_subsampling.py

Fixing empty dataset subsampling error (#40).

---

vires/vires/processes/util/time_series_product.py
vires/vires/tests/util.py
vires/vires/util.py

start_time <= selected_time < end_time

Data selection on an open-closed time interval.

---

vires/vires/processes/fetch_data.py
vires/vires/processes/util/__init__.py
vires/vires/processes/util/filters_subsampling.py
vires/vires/processes/util/time_series_product.py

Added support for TEC, FAC, EEF.
Needed to support different CDF data attributes (different identifiers) and data with multiple equal timestamps.

Integration of new data for service version 2.0

---

vires/vires/admin.py
vires/vires/migrations/0001_initial.py
vires/vires/migrations/0002_auto_20170313_1626.py
vires/vires/models.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/list_jobs.py

* Introduces check not allowing more then two concurrent processes

Wps async with status

---

eoxs_allauth/eoxs_allauth/urls.py
vires/vires/processes/fetch_data.py
vires/vires/processes/util/input_parsers.py

Adresses https://github.com/ESA-VirES/WebClient-Framework/issues/198

Moving feature requests to production

---

vires/vires/data/range_types.json

This is a hot-fix PR adding the EFIx_LP range type to the production branch. This allows registration of the downloaded EFIx_LP product.

Hot-fix: minimal support for the EFIx_LP products.

---

eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
vires/vires/forward_models/chaos6.py
vires/vires/forward_models/swarm_shc.py
vires/vires/management/commands/vires_update_cached_product.py
vires/vires/model_mma.py
vires/vires/processes/util/magnetic_models.py

This PR adds support for the CHAOS-6 MMA models and updatable CHAOS-6 Core models

Support for the CHAOS-6 MMA and updatable CHAOS-6 Core

---

vires/vires/aux_kp.py
vires/vires/processes/fetch_data.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/get_indices.py
vires/vires/processes/util/__init__.py
vires/vires/processes/util/time_series_aux.py

This hot-fix solves the wrongly scaled _Kp_ index values.
https://github.com/ESA-VirES/WebClient-Framework/issues/312

Hot-fix: wrong Kp index values

---

vires/vires/dataset.py
vires/vires/interpolate.py
vires/vires/processes/fetch_data.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/util/__init__.py
vires/vires/processes/util/filters.py
vires/vires/processes/util/filters_subsampling.py
vires/vires/processes/util/resolver.py
vires/vires/processes/util/time_series.py
vires/vires/processes/util/time_series_aux.py
vires/vires/processes/util/time_series_product.py

Adding extra samples to the sub-sampled master product time-line to make sure the slave EEF values are contained.
see https://github.com/ESA-VirES/WebClient-Framework/issues/308

EEF sampling

---

vires/vires/processes/retrieve_field_lines.py

- calculations of the field line apex and ground intersection points
- coordinates in simpler geocentric spherical coordinates
- fields lines no longer colored on the server
- change of the payload format from CSV to MSGPACK and JSON
related to https://github.com/ESA-VirES/WebClient-Framework/pull/325

Enhanced fieldlines

---

vires/setup.cfg
vires/setup.py
vires/vires/cached_products.py
vires/vires/management/commands/vires_update_cached_product.py
vires/vires/model_mma.py
vires/vires/orbit_direction_update.py
vires/vires/processes/get_model_info.py
vires/vires/processes/util/input_parsers.py
vires/vires/processes/util/magnetic_model_file.py
vires/vires/processes/util/magnetic_models.py
vires/vires/processes/util/model_dipole.py
vires/vires/processes/util/model_magmod.py

- extending source product traceability to magnetic models

Models traceability

---

vires/vires/cdf_util.py
vires/vires/locked_file_access.py
vires/vires/migrations/0004_clientstate_customdataset_custommodel.py
vires/vires/models.py
vires/vires/processes/fetch_data.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/util/__init__.py
vires/vires/processes/util/input_parsers.py
vires/vires/processes/util/time_series_custom_data.py
vires/vires/processes/util/time_series_product.py
vires/vires/time_util.py
vires/vires/util.py
vires/vires/views.py
vires/vires/views/__init__.py
vires/vires/views/client_state.py
vires/vires/views/custom_data.py
vires/vires/views/custom_model.py
vires/vires/views/decorators.py
vires/vires/views/exceptions.py

- Custom data upload 
- Custom model upload 
- Client state upload

Data upload

---

vires/vires/processes/fetch_data.py

This PR fixes the EEF extra sampling regression introduced in the v3.0.0 release.

Hot-fix: EEF extra sampling regression

---

vires/custom_data_format_description.md
vires/vires/cdf_util.py
vires/vires/cdf_write_util.py
vires/vires/orbit_direction_update.py
vires/vires/views/custom_data.py

This PR implements support for the CSV data upload.

CSV data upload

---

eoxs_allauth/eoxs_allauth/static/css/form_styles.css
eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
eoxs_allauth/eoxs_allauth/views.py
vires/vires/client_state.py

related to https://github.com/ESA-VirES/WebClient-Framework/pull/339

Support for client-state POST requests

---

eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
vires/setup.py
vires/vires/processes/util/magnetic_models.py

implementing changes requested by https://github.com/ESA-VirES/WebClient-Framework/issues/352

Revised models

---

eoxs_allauth/eoxs_allauth/templates/custom_data_format_description.html
vires/custom_data_format_description.md
vires/vires/cdf_util.py
vires/vires/migrations/0005_auto_20190820_1607.py
vires/vires/models.py
vires/vires/processes/util/model_magmod.py
vires/vires/processes/util/time_series_custom_data.py
vires/vires/readers/common.py
vires/vires/readers/exceptions.py
vires/vires/readers/tests/csv_reader.py
vires/vires/views/client_state.py
vires/vires/views/custom_data.py
vires/vires/views/decorators.py

This PR adds possibility of uploading custom data with missing mandatory `Latitude` and `Longitude` parameters. The missing parameters can be substituted by constant values.
In addition, a definition of a new parameter with a constant value is possible.

Upload extra constant fields

---

vires/vires/processes/get_orbit_timerange.py

see https://github.com/ESA-VirES/WebClient-Framework/issues/370

Fixing orbit number to time range conversion.

---

vires_oauth/vires_oauth/middleware.py
vires_oauth/vires_oauth/signals.py
vires_oauth/vires_oauth/utils.py

This patch fixes the access and user account actions logging in the VirES Oauth identity server.
This PR requires https://github.com/ESA-VirES/VirES/pull/57

Hotfix: OAuth server logging

---

eoxs_allauth/eoxs_allauth/templates/vires/workspace.html

A mere change of the landing page model description.
Related to https://github.com/ESA-VirES/WebClient-Framework/pull/374

CHAOS-6 to CHAOS-7 transition

---

eoxs_allauth/eoxs_allauth/__init__.py
eoxs_allauth/eoxs_allauth/management/commands/_common.py
eoxs_allauth/eoxs_allauth/management/commands/auth_activate_users.py
eoxs_allauth/eoxs_allauth/management/commands/auth_connect_users_to_vires_oauth.py
eoxs_allauth/eoxs_allauth/management/commands/auth_deactivate_users.py
eoxs_allauth/eoxs_allauth/management/commands/auth_export_social_providers.py
eoxs_allauth/eoxs_allauth/management/commands/auth_export_users.py
eoxs_allauth/eoxs_allauth/management/commands/auth_import_social_providers.py
eoxs_allauth/eoxs_allauth/management/commands/auth_import_users.py
eoxs_allauth/eoxs_allauth/management/commands/auth_list_users.py
eoxs_allauth/eoxs_allauth/signals.py
eoxs_allauth/eoxs_allauth/views.py
eoxs_allauth/eoxs_allauth/vires_oauth/decorators.py
eoxs_allauth/eoxs_allauth/vires_oauth/messages.py
eoxs_allauth/eoxs_allauth/vires_oauth/permissions.py
eoxs_allauth/setup.py
vires_oauth/vires_oauth/management/commands/_common.py
vires_oauth/vires_oauth/management/commands/auth_activate_users.py
vires_oauth/vires_oauth/management/commands/auth_deactivate_users.py
vires_oauth/vires_oauth/management/commands/auth_import_apps.py
vires_oauth/vires_oauth/management/commands/auth_import_groups.py
vires_oauth/vires_oauth/management/commands/auth_import_permissions.py
vires_oauth/vires_oauth/management/commands/auth_import_social_providers.py
vires_oauth/vires_oauth/management/commands/auth_import_users.py
vires_oauth/vires_oauth/management/commands/auth_set_user_group.py
vires_oauth/vires_oauth/management/commands/auth_unset_user_group.py

Key features:
- review of the VirES-Server authentication/authorization
- proper blocking of users without the expected permission
- removing unnecessary package dependency

Proper VirES-Server authorization.

---

eoxs_allauth/eoxs_allauth/templates/documents/changelog.html
eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
vires/setup.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/util/magnetic_models.py

This hotfix PR updates the IGRF model to its latest 13th generation and introduces new version-less  model identifier `IGRF`.

Hotfix: IGRF-13

---

vires/vires/cdf_util.py
vires/vires/tests/cdf_util.py
vires/vires/views/custom_data.py

Fixes #143 and #144 issues.
A fix to this issue  https://github.com/ESA-VirES/WebClient-Framework/issues/392 has been amended.

Hotfix: Improving type check of the uploaded CDF files.

---

vires/vires/access_util.py
vires/vires/cdf_util.py
vires/vires/models.py
vires/vires/processes/fetch_data.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/get_collection_info.py
vires/vires/processes/get_time_data.py
vires/vires/processes/list_jobs.py
vires/vires/processes/remove_job.py
vires/vires/processes/util/input_parsers.py
vires/vires/processes/util/time_series/custom_data.py
vires/vires/processes/util/time_series/product.py
vires_oauth/vires_oauth/data/default_groups.json
vires_oauth/vires_oauth/data/default_permissions.json

Implementing optional restricted access to selected collections.

Restricted data access

---

vires/vires/processes/util/filters/temporal_sampling.py

This hotfix PR solves https://github.com/ESA-VirES/WebClient-Framework/issues/405

Hotfix: Fixing extra sample insertion for EEF products.

---

vires/vires/data/product_collections.json
vires/vires/data/product_types.json
vires/vires/management/api/product.py
vires/vires/management/commands/_product/register.py
vires/vires/models.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/util/input_parsers.py
vires/vires/processes/util/time_series/product.py
vires/vires/swarm.py

This PR adds support for observatory (AUX_OBS) products.

AUX_OBS support

---

vires/vires/processes/fetch_fieldlines.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/util/__init__.py
vires/vires/processes/util/parsers/__init__.py
vires/vires/processes/util/parsers/collections.py
vires/vires/processes/util/parsers/filters.py
vires/vires/processes/util/parsers/locations.py
vires/vires/processes/util/parsers/models.py
vires/vires/processes/util/parsers/style.py
vires/vires/processes/util/parsers/variables.py

This PR add a new field-lines server WPS process accepting list of "seed" locations rather than a bounding box.
The field-lines grid generation has been moved to the client side.
This change is required by the new Swarm PRISM use-case.

VIR-350: new fieldlines API

---

vires/vires/data/product_collections.json
vires/vires/data/product_types.json

see https://github.com/ESA-VirES/WebClient-Framework/issues/446

Adding support for the MODx_SC products.

---

vires/vires/data/product_collections.json
vires/vires/data/product_types.json

- product type and collections definitions

Support for SW_EFIxIDM_2_ products

---

eoxs_allauth/eoxs_allauth/templates/documents/changelog.html
eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
vires/vires/data/product_collections.json
vires/vires/data/product_types.json
vires/vires/data/vires_settings.py
vires/vires/hapi/formats/binary.py
vires/vires/hapi/readers/cdf.py
vires/vires/hapi/views/landing_page.py
vires/vires/management/commands/_cached_product/dump.py
vires_oauth/setup.py
vires_oauth/vires_oauth/__init__.py
vires_oauth/vires_oauth/management/commands/_app/export.py
vires_oauth/vires_oauth/management/commands/_app/import_.py

Key features:
- publishing Swarm non-magnetic products via HAPI interface
- HAPI fixes

production release (VirES v3.11.0) 

---

eoxs_allauth/eoxs_allauth/templates/429.html
vires_oauth/vires_oauth/templates/429.html

Hotfix: missing 429 Too Many Requests template

---

vires/vires/processes/util/time_series/product.py

Fixing https://github.com/ESA-VirES/VirES-Python-Client/issues/96

Hotfix: Fixing OBS time subsetting.

---

vires/vires/processes/util/time_series/data_extraction.py

Fixing https://github.com/ESA-VirES/VirES-Server/issues/201

Hotfix: Fixing extraction of CDF NRV variables.

---

vires/vires/dataset.py
vires/vires/processes/util/time_series/base_product.py
vires/vires/processes/util/time_series/product.py
vires/vires/tests/dataset.py

See https://github.com/ESA-VirES/VirES-Server/issues/204 for more details.

Hotfix: OMNI out-of-range time interpolation

---

vires/vires/hapi/time_series.py

Hotfix: fixing HAPI model caching

---

vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py

Hotfix: broken slave data filtering and interpolation

---

vires/vires/processes/util/time_series/data_extraction.py

Hotfix: broken subsetting of AUX_OBS products

---

vires/vires/hapi/time_series.py
vires/vires/processes/fetch_data.py
vires/vires/processes/fetch_filtered_data.py
vires/vires/processes/fetch_filtered_data_async.py
vires/vires/processes/get_indices.py
vires/vires/processes/get_time_data.py
vires/vires/processes/retrieve_bubble_index.py
vires/vires/processes/retrieve_continuous_segments.py
vires/vires/processes/util/amps_inputs.py
vires/vires/processes/util/models/magnetic_model/model_setup.py
vires/vires/processes/util/parsers/collections.py
vires/vires/processes/util/spacecraft_subtraction.py
vires/vires/processes/util/time_series/__init__.py
vires/vires/processes/util/time_series/base_product.py
vires/vires/processes/util/time_series/cached_model.py
vires/vires/processes/util/time_series/custom_data.py
vires/vires/processes/util/time_series/data_extraction.py
vires/vires/processes/util/time_series/product.py
vires/vires/processes/util/time_series/product_source.py
vires/vires/util.py

This PR implements concept of a mixed virtual collection.
Multiple collections can be composed with the `+` sign in order to fill gaps in the previous collections.
E.g., `SW_OPER_MAGA_LR_1B+SW_FAST_MAGA_LR_1B` tries to extract data from the `SW_OPER_MAGA_LR_1B` first and no data found the gap is filled from the `SW_FAST_MAGA_LR_1B`.
This feature has been implemented to simplify visualization of Swarm FAST products in the web client in the time period before the consolidated OPER product becomes available.

Support for Swarm FAST product visualization

---

vires/vires/processes/util/parsers/collections.py

Hotfix: broken collection parsing for multi-site OBS/VOBS requests

---

eoxs_allauth/eoxs_allauth/templates/documents/changelog.html
eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
vires/vires/amps.py
vires/vires/aux_f107.py
vires/vires/processes/util/f107.py
vires/vires/processes/util/magnetic_model_renderer.py
vires/vires/processes/util/models/magnetic_model/mio_model.py
vires/vires/processes/util/models/magnetic_model/source_model.py
vires/vires/processes/util/time_series/indices.py

Hotfix: fixing the MIO models evaluation (F10.7 averaging)

---

vires/vires/processes/retrieve_continuous_segments.py

Hotfix: broken extraction of time segments for AEJxLP* products

---

vires/vires/processes/util/orbit_info.py

Note that this hot-fix just mitigates the issue and the proper fix still has to be  implemented.
For more details see #226.

Hoftix: missing orbit variables for the mixed OPER+FAST collections

---

vires/vires/aux_common.py
vires/vires/aux_dst.py
vires/vires/aux_f107.py
vires/vires/aux_kp.py
vires/vires/cdf_util.py
vires/vires/orbit_counter/reader.py
vires/vires/orbit_direction/merge.py
vires/vires/orbit_direction/reader.py
vires/vires/orbit_direction/table.py
vires/vires/orbit_direction/tests/merge.py
vires/vires/orbit_direction/update.py
vires/vires/processes/util/orbit_info.py
vires/vires/processes/util/time_series/auxiliary_data.py
vires/vires/processes/util/time_series/base.py
vires/vires/processes/util/time_series/indices.py
vires/vires/processes/util/time_series/orbit_counter.py
vires/vires/processes/util/time_series/orbit_direction.py
vires/vires/tests/aux_common.py
vires/vires/tests/cdf_util.py
vires/vires/tests/orbit_direction.py

Hotfix: orbit direction for mixed OPER and FAST collections

---

vires/vires/data/product_types.json

Hotfix: Upgrading the COGE MAG ML product definition to the new 0301 baseline.

---

vires/vires/data/product_collections.json
vires/vires/data/product_types.json

This PR adds support for the CHAMP MAG products.

Implementing support for CHAMP MAG products

---

eoxs_allauth/eoxs_allauth/static/other/owserrorstyle.xsl
eoxs_allauth/eoxs_allauth/templates/account/access_token_manager.html
eoxs_allauth/eoxs_allauth/templates/account/base.html
eoxs_allauth/eoxs_allauth/templates/vires/base.html
eoxs_allauth/eoxs_allauth/templates/vires/workspace.html

related to https://github.com/ESA-VirES/WebClient-Framework/pull/480

Client packaging maintenance

---

vires/vires/processes/get_observatories.py

Hotfix: fixing swapped observatories coordinates

---

vires/vires/management/api/cached_magnetic_model/file_format.py
vires/vires/management/api/cached_magnetic_model/flush.py
vires/vires/management/api/cached_magnetic_model/seed.py
vires/vires/management/api/cached_magnetic_model/stats.py
vires/vires/management/commands/_cached_model/common.py
vires/vires/management/commands/_cached_model/flush.py
vires/vires/management/commands/_cached_model/seed.py
vires/vires/management/commands/_cached_model/stats.py
vires/vires/util_multiprocessing.py

The cache operations requires processing of large amount of independent cache files.
Parallelization using multiple processes speeds up the cache operations significantly.

Using multi-processing to speedup model cache operations.

---

eoxs_allauth/eoxs_allauth/templates/documents/changelog.html
eoxs_allauth/eoxs_allauth/templates/vires/workspace.html
vires/vires/data/product_collections.json

This PR adds support for the new Swarm FAST TEC collections.

Hotfix: support for the new Swarm FAST TEC collections
